### ISSUE TITLE
[+] Filters - Fields containing enum subfields are not available as filter on the UI

### ISSUE THREAD

**Issue by GautierT** [ForestAdmin/forest-express#236]
## Expected behavior

With a field like this in my model

```
status: {
    name: {
      type: String,
      enum: ['EVENT.ONE', 'EVENT.TWO', 'EVENT.THREE'],
    },
    event_id: String,
    description: String,
    updated_at: Date,
  },
```
i expect to be able to filter by `status.name`

## Actual behavior

Only `event_id`, `description` and `updated_at` subfields are available in the Forest UI. `status` is not.

![image](https://user-images.githubusercontent.com/6089653/58867649-1de40580-86bb-11e9-9479-eaab372f0619.png)

## Failure Logs

No logs

## Context

TODO: Please provide any relevant information about your setup.

* Package Version: 
- Forest-express-mongoose and forest-express : 3.1.1
* Express Version: 4.17.1

**Comment by arnaudbesnier** [comment]
Hi @GautierT is this field displayed properly in the records list/details?

**Comment by GautierT** [comment]
@arnaudbesnier yep ! 

![image](https://user-images.githubusercontent.com/6089653/58870127-d8760700-86bf-11e9-8114-afff53c5963e.png)

**Comment by GautierT** [comment]
Any news on this ?

**Comment by arnaudbesnier** [comment]
Hi @GautierT,
This is something that is not supported yet.
But let me create a story for this and we'll try to support this.

Thanks for your patience.

**Comment by slimee** [comment]
Hi @GautierT,
I'm happy to say you that this feature will be available in next release :)

Best

**Comment by GautierT** [comment]
@slimee : When could i expect the next release ?
This bug is still here...

**Comment by slimee** [comment]
Hi @GautierT,

Sad to read that. Let me check.

**Comment by Sidnioulz** [comment]
Hi @GautierT,

I cannot reproduce the bug. I created a new MongoDB project and made two collections, with one referencing the other and the referenced collection having an enum field. I can see it in filters and I can select any value for that enum subfield.

This being said, it's possible there is another bug that your specific model triggers, which we haven't accounted for. Would you please be kind enough to share your models with us along with an empty database schema so we can test again with your own setup?

For reference, these are the package versions I used in my tests, as there have been a few updates since the issue was originally opened:

* express: 4.16.2
* forest-express: 4.0.1
* forest-express-mongoose: 4.0.3
* lumber-forestadmin: 1.3.0
* mongoose: 5.3.16

Thanks,
