### ISSUE TITLE
Using a path in APPLICATION_URL fails

### ISSUE THREAD

**Issue by giregk** [ForestAdmin/forest-express#685]
## Expected behavior

I would like to user https://my-domain.com/path as my Forest Admin server URL. It should work fine.

## Actual behavior

This setup partially works since I can finish the deployment, but then I can't access my data.
The problem comes from an "OPTIONS" request that is sent to my `domain.com/forest/authentication/callback` instead of `my-domain.com/path/forest/authentication/callback`.
Hence the request is not recognized by my reverse proxy and fails.

## Context

* Package Version: 8.0.0

## Solution

=> This bug comes from routes/authentication.js, in function getCallbackUrl, because of
```
var url = new URL("/forest/".concat(CALLBACK_AUTHENTICATION_ROUTE), applicationUrl);
```
(`new URL` removes all paths in applicationUrl)

To fix it, new URL should be given the absolute URL already concatenated.
```
var url = new URL(applicationUrl+"/forest/".concat(CALLBACK_AUTHENTICATION_ROUTE));
```

**Comment by ghusse** [comment]
Hello @giregk,

We recently fixed this bug, as you can see in the current source code, [this code](https://github.com/ForestAdmin/forest-express/blob/master/src/routes/authentication.js#L17) has been changed [to call this function](https://github.com/ForestAdmin/forest-express/blob/d084e6faa93707a123707b10746a24f85d818c9c/src/utils/join-url.js#L6) that correctly joins the URL and path.

It has been fixed with #667, released with v8.0.4
